<?php

return [
    'specialists' => [
        'Allergist/Immunologist',
        'Anesthesiologist',
        'Cardiologist',
        'Dermatologist',
        'Dietician',
        'Emergency Medicine Specialist',
        'Endocrinologist',
        'Family Medicine Physician',
        'Gastroenterologist',
        'Geriatrician',
        'Gynecologist',
        'Hematologist',
        'Infectious Disease Specialist',
        'Internist',
        'Nephrologist',
        'Neurologist',
        'Neurosurgeon',
        'Obstetrician/Gynecologist (OB/GYN)',
        'Oncologist',
        'Ophthalmologist',
        'Orthopedic Surgeon',
        'Otolaryngologist (ENT Specialist)',
        'Pediatrician',
        'Plastic Surgeon',
        'Psychiatrist',
        'Pulmonologist',
        'Radiologist',
        'Rheumatologist',
        'Sleep Medicine Specialist',
        'Spine and Trauma Surgeon',
        'Sports Medicine Specialist',
        'General Surgeon',
        'Cardiothoracic Surgeon',
        'Urologist',
        'Vascular Surgeon',
        'General Practitioner',
        'Medical Officer',
        'Primary Care Physician',
        'Dentist',
        'Nutritionist',
    ]
];